# Arquivo de configuração para meu servidor

# Configurações obrigatórias (sem elas o servidor não vai funcionar)
# --------------------------
# Métodos que foram implementados
implemented_methods = ["GET", "HEAD", "OPTIONS"]

# Versões do HTTP que suporta
http_version = "HTTP/1.1"

# Porta padrão
port = 9999

# URL Padrão
host = "localhost"

# Raiz dos recursos acessados pelo servidor
content_root = "../Content"
# --------------------------

# Nome do Servidor
server_name = "migs' Minimal Server"

# Caminho para páginas de erro
error_path = "/errors/"

# Caminhos e Arquivos Proibidos
[Forbidden]
paths = ["..", "~", "//"]
files = [".sh", ".log"]

# Caminhos e Arquivos Permitidos
[Allowed]
paths = ["Content"]
files = [".html", ".css", ".scss", ".js", ".txt", ".json", ".csv", ".xml", ".pdf", ".ico", ".jpg", ".png"]